<?php

$additionalReplacementValues = [
    '%PARTICIPATION_STATUSCODE_ATTENDED%' => CrmValues::PARTICIPATION_STATUSCODE_ATTENDED,
    '%PARTICIPATION_STATUSCODE_CANCELLED_WITH_SUBSTITUTE%' =>
        CrmValues::PARTICIPATION_STATUSCODE_CANCELLED_WITH_SUBSTITUTE,
    '%PARTICIPATION_STATUSCODE_CANCELLED_WITHOUT_SUBSTITUTE%' =>
        CrmValues::PARTICIPATION_STATUSCODE_CANCELLED_WITHOUT_SUBSTITUTE,
];
